export type ElementType =
  | "button"
  | "checkboxes"
  | "datepicker"
  | "image"
  | "multi_static_select"
  | "multi_external_select"
  | "multi_users_select"
  | "multi_conversations_select"
  | "multi_channels_select"
  | "overflow"
  | "plain_text_input"
  | "radio_buttons"
  | "static_select"
  | "external_select"
  | "users_select"
  | "conversations_select"
  | "channels_select";
